[platformio]
description = RoBorregos Candidates 2026 autonomous robot
default_envs = main

; Configuración base compartida
[env]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
upload_port = COM5
monitor_port = COM5

build_flags = 
	-Isrc
	-Iinclude

lib_deps = 
	adafruit/Adafruit GFX Library
	adafruit/Adafruit SSD1306
	adafruit/Adafruit BusIO
	adafruit/Adafruit MPU6050
	adafruit/Adafruit TCS34725
	adafruit/Adafruit_VL53L0X
	pololu/QTRSensors
	arduino-libraries/Servo

; 1. Entorno Principal (Compila todo src/ y lib/)
[env:main]
build_src_filter = +<*> -<../test/>

; 2. Pruebas individuales de Hardware
[env:test_motors]
build_src_filter = +<../test/motor_test.cpp>

[env:test_encoders]
build_src_filter = +<../test/encoder_test.cpp>

[env:test_vl53_color]

build_src_filter = +<../test/testvl53color_test.cpp>

[env:test_imu]
build_src_filter = +<../test/imu_test.cpp>

[env:test_qtr]
build_src_filter = +<../test/qtr_test.cpp>

[env:test_servo]
build_src_filter = +<../test/servo_test.cpp>

[env:test_oled]
build_src_filter = +<../test/oled_test.cpp>

[env:test_color]
build_src_filter = +<../test/color_test.cpp>

[env:test_scanner]
build_src_filter = +<../test/scanner_test.cpp>

; 3. Suite standalone de pruebas 2.0
[env:test_01_kinematics]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
build_flags = -Iinclude -Isrc
build_src_filter = +<../tests_2.0/01_test_kinematics.cpp>

[env:test_02_imu]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
build_flags = -Iinclude -Isrc
build_src_filter = +<../tests_2.0/02_test_imu.cpp>

[env:test_03_distance]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
build_flags = -Iinclude -Isrc
build_src_filter = +<../tests_2.0/03_test_distance.cpp>

[env:test_04_color_line]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
build_flags = -Iinclude -Isrc
build_src_filter = +<../tests_2.0/04_test_color_line.cpp>

[env:test_05_gripper_ball]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
build_flags = -Iinclude -Isrc
build_src_filter = +<../tests_2.0/05_test_gripper_ball.cpp>