[platformio]
description = RoBorregos Candidates 2026 autonomous robot

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200

upload_port = COM5
monitor_port = COM5

lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
    adafruit/Adafruit BusIO
    adafruit/Adafruit MPU6050
    adafruit/Adafruit TCS34725
    adafruit/Adafruit_VL53L0X
    pololu/QTRSensors
    arduino-libraries/Servo

#
build_src_filter = +<../test/motor_test.cpp> -<main.cpp>
